In [1]:
%%writefile compute.py
import numpy as np
def angle_v2(vec1, vec2):
    #compute angle between 2 vectors. ... from google
    
    # 각 벡터의 각도 계산 (x축 기준)
    angle1 = np.arctan2(vec1[:,1], vec1[:,0])
    angle2 = np.arctan2(vec2[:,1], vec2[:,0])

    # 두 각도의 차이 계산
    angle_diff_rad = angle2 - angle1

    # 절대값 및 360도 조정 (필요에 따라)
    angle_diff_deg = np.degrees(angle_diff_rad)
    #angle_diff_deg = np.where( angle_diff_deg < 0, angle_diff_deg + 360, angle_diff_deg )

    return angle_diff_deg


Writing compute.py


In [3]:
import compute

In [7]:
import dataproc

In [22]:
import numpy as np

In [9]:
A = dataproc.ExampleData('1.xlsx')

In [45]:
TEST_DATA_A = np.array(([1,0],))
TEST_DATA_B = np.array(([1,1],))

In [46]:
compute.angle_v2(TEST_DATA_A,   TEST_DATA_B)

array([45.])

In [20]:
A.df[['torso_x','torso_y']].loc[[0,1]].values

array([[-53.08918, -76.51717],
       [-52.14709, -77.80215]])

In [27]:
np.array(([0,1],[0,0]))

array([[0, 1],
       [0, 0]])

In [32]:
np.array(([0,1],))

array([[0, 1]])

In [42]:
np.arctan2(1,10)

np.float64(0.09966865249116202)

In [39]:
np.arctan2(1,0)

np.float64(1.5707963267948966)