In [1]:
import pandas as pd

In [2]:
import numpy as np

In [130]:
df1=pd.DataFrame()
df1=pd.read_excel('../data/1.xlsx')
df1=df1.dropna()

In [131]:
df1

,timestamp,head_x,head_y,head_z,torso_x,torso_y,torso_z,waist_x,waist_y,waist_z,...,r_hip_z,r_knee_x,r_knee_y,r_knee_z,l_ankle_x,l_ankle_y,l_ankle_z,r_ankle_x,r_ankle_y,r_ankle_z
0,1743993607,-66.57459,346.6133,2153.312,-53.08918,-76.51717,2227.077,-42.61894,-253.0159,2199.219,...,2200.213,-146.0421,-645.2217,2094.135,139.9366,-954.6445,2234.752,-180.1308,-968.9515,2229.294
1,1743993607,-55.37650,341.3134,2148.882,-52.14709,-77.80215,2225.404,-43.16278,-255.7176,2202.311,...,2200.134,-147.0702,-660.8210,2072.728,141.4262,-959.2802,2230.064,-180.6705,-976.3017,2226.266
2,1743993607,-55.37650,341.3134,2148.882,-52.14709,-77.80215,2225.404,-43.16278,-255.7176,2202.311,...,2200.134,-147.0702,-660.8210,2072.728,141.4262,-959.2802,2230.064,-180.6705,-976.3017,2226.266
3,1743993607,-55.37650,341.3134,2148.882,-52.14709,-77.80215,2225.404,-43.16278,-255.7176,2202.311,...,2200.134,-147.0702,-660.8210,2072.728,141.4262,-959.2802,2230.064,-180.6705,-976.3017,2226.266
4,1743993608,-45.28284,330.4109,2149.211,-51.05178,-87.53446,2226.210,-43.04076,-265.1855,2202.331,...,2200.013,-151.5682,-664.8762,2056.333,110.5179,-1002.7690,2058.162,-180.9913,-975.9042,2219.510
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
442,1743993622,-71.18983,360.3356,2118.724,-50.02530,-57.78058,2173.144,-44.92595,-239.8437,2154.254,...,2160.997,-161.4635,-664.4786,2077.935,135.1745,-976.7439,2232.596,-175.5972,-990.8358,2226.992
443,1743993622,-71.18983,360.3356,2118.724,-50.02530,-57.78058,2173.144,-44.92595,-239.8437,2154.254,...,2160.997,-161.4635,-664.4786,2077.935,135.1745,-976.7439,2232.596,-175.5972,-990.8358,2226.992
444,1743993622,-71.09723,365.8696,2118.778,-50.38910,-49.04067,2167.271,-44.08286,-232.1081,2148.591,...,2155.674,-159.5926,-660.0185,2082.340,134.4717,-975.1656,2235.963,-177.6347,-985.7233,2226.622
445,1743993622,-71.09723,365.8696,2118.778,-50.38910,-49.04067,2167.271,-44.08286,-232.1081,2148.591,...,2155.674,-159.5926,-660.0185,2082.340,134.4717,-975.1656,2235.963,-177.6347,-985.7233,2226.622


In [132]:
df_ant = df1[['l_hip_x','l_hip_y','l_knee_x','l_knee_y','l_ankle_x','l_ankle_y']]

In [133]:
df_ant

,l_hip_x,l_hip_y,l_knee_x,l_knee_y,l_ankle_x,l_ankle_y
0,59.56746,-265.5242,99.13966,-632.0627,139.9366,-954.6445
1,59.73900,-281.9015,101.91260,-646.1818,141.4262,-959.2802
2,59.73900,-281.9015,101.91260,-646.1818,141.4262,-959.2802
3,59.73900,-281.9015,101.91260,-646.1818,141.4262,-959.2802
4,60.36124,-289.7710,104.66220,-650.3589,110.5179,-1002.7690
...,...,...,...,...,...,...
442,51.04284,-281.1733,93.28984,-654.5800,135.1745,-976.7439
443,51.04284,-281.1733,93.28984,-654.5800,135.1745,-976.7439
444,53.36913,-277.3993,92.71281,-653.2104,134.4717,-975.1656
445,53.36913,-277.3993,92.71281,-653.2104,134.4717,-975.1656


In [134]:
pd.set_option('mode.chained_assignment', None)
df_ant['l_tibia_x'] = df1['l_knee_x'] - df1['l_ankle_x']
df_ant['l_tibia_y'] = df1['l_knee_y'] - df1['l_ankle_y']
df_ant['l_femur_x'] = df1['l_hip_x'] - df1['l_knee_x']
df_ant['l_femur_y'] = df1['l_hip_y'] - df1['l_knee_y']

In [135]:
df_ant

,l_hip_x,l_hip_y,l_knee_x,l_knee_y,l_ankle_x,l_ankle_y,l_tibia_x,l_tibia_y,l_femur_x,l_femur_y
0,59.56746,-265.5242,99.13966,-632.0627,139.9366,-954.6445,-40.79694,322.5818,-39.57220,366.5385
1,59.73900,-281.9015,101.91260,-646.1818,141.4262,-959.2802,-39.51360,313.0984,-42.17360,364.2803
2,59.73900,-281.9015,101.91260,-646.1818,141.4262,-959.2802,-39.51360,313.0984,-42.17360,364.2803
3,59.73900,-281.9015,101.91260,-646.1818,141.4262,-959.2802,-39.51360,313.0984,-42.17360,364.2803
4,60.36124,-289.7710,104.66220,-650.3589,110.5179,-1002.7690,-5.85570,352.4101,-44.30096,360.5879
...,...,...,...,...,...,...,...,...,...,...
442,51.04284,-281.1733,93.28984,-654.5800,135.1745,-976.7439,-41.88466,322.1639,-42.24700,373.4067
443,51.04284,-281.1733,93.28984,-654.5800,135.1745,-976.7439,-41.88466,322.1639,-42.24700,373.4067
444,53.36913,-277.3993,92.71281,-653.2104,134.4717,-975.1656,-41.75889,321.9552,-39.34368,375.8111
445,53.36913,-277.3993,92.71281,-653.2104,134.4717,-975.1656,-41.75889,321.9552,-39.34368,375.8111


In [136]:
def angle_v2(vec1, vec2):
    # from google
    #import math
    import numpy as np

    np.array 
    
    # 각 벡터의 각도 계산 (x축 기준)
    angle1 = np.arctan2(vec1[:,1], vec1[:,0])
    angle2 = np.arctan2(vec2[:,1], vec2[:,0])

    # 두 각도의 차이 계산
    angle_diff_rad = angle2 - angle1

    # 절대값 및 360도 조정 (필요에 따라)
    angle_diff_deg = np.degrees(angle_diff_rad)
    #angle_diff_deg = np.where( angle_diff_deg < 0, angle_diff_deg + 360, angle_diff_deg )

    return angle_diff_deg

In [137]:
angle_v2(df_ant[['l_tibia_x','l_tibia_y']].values,       df_ant[['l_femur_x','l_femur_y']].values     )[0:50]

array([-1.04603804, -0.58893883, -0.58893883, -0.58893883,  6.05217421,
        6.05217421,  6.05217421,  7.00831698,  7.00831698,  7.00831698,
        7.00831698,  3.63826577,  5.04013666,  5.59643378,  4.93305672,
        5.04789869,  5.45474378,  6.47240246,  6.65108094,  6.65108094,
        6.65108094,  6.65108094,  5.73144701,  5.73144701,  5.73144701,
        4.13124741,  4.13124741,  4.13124741,  3.28872779,  3.28872779,
        3.00636015,  3.00636015,  3.00636015,  2.59694864,  2.59694864,
        2.59694864,  0.34142134,  0.34142134,  0.34142134, -1.85475768,
       -1.85475768, -3.55181251, -2.89652082, -2.43232733, -2.67288565,
       -3.81630449, -3.77114997, -2.64969975, -2.64969975, -2.64969975])

In [138]:
#lateral view
df_lat = df1[['torso_y', 'torso_z', 'waist_y','waist_z','l_hip_y','l_hip_z','l_knee_y','l_knee_z','l_ankle_y','l_ankle_z']]

In [139]:
df_lat['tor_wai_y'] = df_lat['torso_y'] - df_lat['waist_y']
df_lat['tor_wai_z'] = df_lat['torso_z'] - df_lat['waist_z']
df_lat['l_hip_wai_y'] = df_lat['waist_y'] - df_lat['l_hip_y']
df_lat['l_hip_wai_z'] = df_lat['waist_z'] - df_lat['l_hip_z']
df_lat['l_tibia_y'] = df_lat['l_knee_y'] - df_lat['l_ankle_y']
df_lat['l_tibia_z'] = df_lat['l_knee_z'] - df_lat['l_ankle_z']

In [140]:
#low back arch
angle_v2(df_lat[['tor_wai_y', 'tor_wai_z']].values, df_lat[['l_hip_wai_y','l_hip_wai_z']].values)[1:50]

array([-19.52826228, -19.52826228, -19.52826228, -20.47174008,
       -20.47174008, -20.47174008, -23.73355201, -23.73355201,
       -23.73355201, -23.73355201, -40.25215899, -36.58546662,
       -33.60983192, -49.37144954, -53.70712933, -46.33269846,
       -47.13091661, -52.8805865 , -52.8805865 , -52.8805865 ,
       -52.8805865 , -58.33710421, -58.33710421, -58.33710421,
       -35.0178035 , -35.0178035 , -35.0178035 , -16.99112836,
       -16.99112836, -14.70892681, -14.70892681, -14.70892681,
       -17.2000072 , -17.2000072 , -17.2000072 , -20.71642556,
       -20.71642556, -20.71642556, -26.24926783, -26.24926783,
       -26.19067844, -17.44323576, -11.04570688,  -7.11688621,
        -8.87806252, -10.47235255,  -9.91682923,  -9.91682923,
        -9.91682923])

In [141]:
#torso lean forward
angle_v2(df_lat[['l_tibia_y','l_tibia_z']].values, df_lat[['tor_wai_y', 'tor_wai_z']].values)[1:200]

array([34.02183777, 34.02183777, 34.02183777,  7.34679683,  7.34679683,
        7.34679683,  8.39086991,  8.39086991,  8.39086991,  8.39086991,
       39.14362165, 39.85861378, 42.28125645, 44.03910633, 45.81277677,
       47.1871012 , 48.74229991, 49.11906927, 49.11906927, 49.11906927,
       49.11906927, 46.83035541, 46.83035541, 46.83035541, 43.27326755,
       43.27326755, 43.27326755, 42.39249222, 42.39249222, 43.77418098,
       43.77418098, 43.77418098, 44.22042762, 44.22042762, 44.22042762,
       44.62393332, 44.62393332, 44.62393332, 43.88401119, 43.88401119,
       41.89189449, 41.84691539, 41.4524965 , 40.05328272, 38.95191127,
       38.36155005, 38.12047115, 38.12047115, 38.12047115, 38.3280776 ,
       38.3280776 , 38.3280776 , 39.00368171, 39.00368171, 39.00368171,
       37.17787891, 37.17787891, 37.17787891, 37.42534863, 37.42534863,
       37.42534863, 37.42534863, 37.57295551, 37.57295551, 37.57295551,
       36.56585065, 36.56585065, 36.31812527, 36.31812527, 36.31

In [142]:
df_lat[30:70]

,torso_y,torso_z,waist_y,waist_z,l_hip_y,l_hip_z,l_knee_y,l_knee_z,l_ankle_y,l_ankle_z,tor_wai_y,tor_wai_z,l_hip_wai_y,l_hip_wai_z,l_tibia_y,l_tibia_z
30,-221.1831,2239.191,-398.5157,2230.671,-430.2256,2237.387,-746.2056,1994.084,-1025.701,2237.247,177.3326,8.520,31.7099,-6.716,279.4954,-243.163
31,-221.1831,2239.191,-398.5157,2230.671,-430.2256,2237.387,-746.2056,1994.084,-1025.701,2237.247,177.3326,8.520,31.7099,-6.716,279.4954,-243.163
32,-221.1831,2239.191,-398.5157,2230.671,-430.2256,2237.387,-746.2056,1994.084,-1025.701,2237.247,177.3326,8.520,31.7099,-6.716,279.4954,-243.163
33,-231.8995,2241.046,-408.4230,2231.109,-439.5533,2238.858,-750.6522,1993.069,-1033.651,2239.063,176.5235,9.937,31.1303,-7.749,282.9988,-245.994
34,-231.8995,2241.046,-408.4230,2231.109,-439.5533,2238.858,-750.6522,1993.069,-1033.651,2239.063,176.5235,9.937,31.1303,-7.749,282.9988,-245.994
35,-231.8995,2241.046,-408.4230,2231.109,-439.5533,2238.858,-750.6522,1993.069,-1033.651,2239.063,176.5235,9.937,31.1303,-7.749,282.9988,-245.994
36,-250.3996,2242.472,-426.4955,2231.999,-459.7153,2242.354,-758.7940,1991.497,-1042.533,2240.070,176.0959,10.473,33.2198,-10.355,283.7390,-248.573
37,-250.3996,2242.472,-426.4955,2231.999,-459.7153,2242.354,-758.7940,1991.497,-1042.533,2240.070,176.0959,10.473,33.2198,-10.355,283.7390,-248.573
38,-250.3996,2242.472,-426.4955,2231.999,-459.7153,2242.354,-758.7940,1991.497,-1042.533,2240.070,176.0959,10.473,33.2198,-10.355,283.7390,-248.573
39,-262.8572,2243.490,-437.7896,2232.693,-468.7188,2245.642,-760.0178,1991.223,-1046.820,2234.898,174.9324,10.797,30.9292,-12.949,286.8022,-243.675


In [143]:
from scipy.signal import argrelextrema
import scipy

In [144]:
x = df_lat['torso_y'].rolling(window=25).mean().values
# Find indices of local maxima using np.greater as the comparator
maxima_indices = argrelextrema(x, np.less)

print("Data array:", x)
print("Indices of local maxima:", maxima_indices)
# Output: Indices of local maxima: (array([3, 6]),) 

Data array: [         nan          nan          nan          nan          nan
          nan          nan          nan          nan          nan
          nan          nan          nan          nan          nan
          nan          nan          nan          nan          nan
          nan          nan          nan          nan -139.350432
 -144.6214892 -149.8411472 -155.0608052 -160.3599192 -165.2697408
 -170.6156864 -175.961632  -180.747788  -185.9626    -191.177412
 -196.392224  -201.421904  -206.149564  -210.17032   -214.186156
 -217.882796  -221.599008  -225.093216  -228.482644  -232.171468
 -236.151944  -240.135332  -243.473092  -246.810852  -250.148612
 -253.101044  -256.053476  -259.005908  -261.457968  -263.910028
 -265.925964  -267.406576  -268.887188  -269.939144  -270.601256
 -271.263368  -271.185476  -271.107584  -270.55562   -269.505352
 -268.455084  -266.733408  -264.867336  -262.354216  -259.5417
 -256.437532  -252.96372   -249.148484  -244.833312  -240.160968
 -235.4344

In [84]:
peaks, _ = scipy.signal.find_peaks(x)
#출처: https://super-master.tistory.com/90 [MJ Career Orchestration:티스토리]

In [52]:
peaks

array([  4,   9,  12,  18,  23,  25,  30,  34,  36,  43,  45,  64,  66,
        68,  70,  73,  75,  78,  89,  92,  95,  97,  99, 104, 106, 120,
       124, 127, 132, 135, 139, 153, 156, 159, 162, 165, 178, 189, 191,
       194, 198, 210, 212, 215, 218, 222, 227, 231, 242, 245, 247, 251,
       256, 258, 261, 275, 279, 281, 286, 288])