In [1]:
import pandas as pd

In [2]:
import numpy as np

In [21]:
df1=pd.read_excel('../data/4.xlsx')

In [22]:
df1

,timestamp,head_x,head_y,head_z,torso_x,torso_y,torso_z,waist_x,waist_y,waist_z,...,r_hip_z,r_knee_x,r_knee_y,r_knee_z,l_ankle_x,l_ankle_y,l_ankle_z,r_ankle_x,r_ankle_y,r_ankle_z
0,1745902161,-55.827060,452.776000,2256.349000,-8.589788,-46.445630,2456.054574,-11.476924,-288.092188,2548.472704,...,2610.742919,-158.138462,-808.252767,2647.366011,184.149087,-1239.500686,2662.635675,-216.254749,-1291.341201,2681.851566
1,1745902161,-55.662468,443.680069,2255.534015,-8.880306,-47.249917,2550.045473,-11.288994,-265.974698,2569.248279,...,2626.830046,-160.701638,-831.511317,2536.473171,183.880384,-1241.898209,2504.922929,-221.110197,-1288.180608,2746.310804
2,1745902161,-55.662468,443.680069,2255.534015,-7.982223,-69.252356,2541.725718,-10.974598,-266.384842,2573.346661,...,2729.016387,-156.399549,-820.171016,2558.478415,196.647998,-1179.951554,2801.257686,-220.325607,-1180.001105,2607.530292
3,1745902161,-55.662468,443.680069,2255.534015,-8.300296,-115.668437,2576.150664,-9.836442,-336.098893,2561.674202,...,2626.869004,-154.713555,-840.264884,2582.042984,193.411557,-1168.444279,2841.110996,-223.716550,-1286.802618,2595.407049
4,1745902161,-55.222988,416.846417,2255.213920,-8.135528,-110.783699,2537.074331,-10.337059,-328.342306,2714.477583,...,2689.689621,-158.014725,-831.614317,2514.756104,201.103875,-1165.892635,2717.337183,-211.842938,-1243.741908,2732.845330
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
304,1745902171,-42.067361,452.110793,2230.480329,-4.386789,-19.476487,2529.370552,-6.705935,-205.301837,2431.323683,...,2564.342109,-149.897007,-801.130534,2594.501249,186.267584,-1123.438584,2700.560450,-214.141822,-1090.382390,2756.976167
305,1745902171,-42.067361,452.110793,2230.480329,4.190194,4.108042,2459.711514,2.017044,-195.726803,2481.780290,...,2619.171719,-136.099150,-783.234231,2619.954201,180.154902,-1132.372738,2788.677432,-216.677760,-1193.929603,2571.766029
306,1745902171,-42.067361,452.110793,2230.480329,4.320268,8.230436,2514.683065,1.901079,-184.063544,2579.058793,...,2577.358939,-147.063852,-743.307687,2675.657789,191.566231,-1106.596699,2832.879180,-203.823994,-1125.397462,2569.512704
307,1745902171,-41.910100,443.106957,2230.080484,4.151057,8.288149,2364.732426,1.779079,-187.223885,2489.923143,...,2572.415929,-147.037869,-747.263248,2630.630989,175.742054,-1128.854822,2574.219035,-215.869739,-1046.488934,2783.817009


In [23]:
df_ant = df1[['l_hip_x','l_hip_y','l_knee_x','l_knee_y','l_ankle_x','l_ankle_y']]

In [24]:
df_ant

,l_hip_x,l_hip_y,l_knee_x,l_knee_y,l_ankle_x,l_ankle_y
0,107.733394,-361.112112,130.113143,-845.492115,184.149087,-1239.500686
1,112.604582,-350.280776,140.102875,-782.229191,183.880384,-1241.898209
2,110.778499,-376.979206,145.040137,-829.152187,196.647998,-1179.951554
3,108.371615,-400.368206,139.998511,-887.184110,193.411557,-1168.444279
4,109.472398,-386.986860,151.076787,-879.063208,201.103875,-1165.892635
...,...,...,...,...,...,...
304,94.104964,-336.745144,135.177828,-762.599874,186.267584,-1123.438584
305,88.028521,-349.899483,127.370178,-737.610897,180.154902,-1132.372738
306,88.060778,-343.274659,129.263875,-751.073776,191.566231,-1106.596699
307,92.255395,-364.030771,132.946568,-729.269821,175.742054,-1128.854822


In [25]:
pd.set_option('mode.chained_assignment', None)
df_ant['l_tibia_x'] = df1['l_knee_x'] - df1['l_ankle_x']
df_ant['l_tibia_y'] = df1['l_knee_y'] - df1['l_ankle_y']
df_ant['l_femur_x'] = df1['l_hip_x'] - df1['l_knee_x']
df_ant['l_femur_y'] = df1['l_hip_y'] - df1['l_knee_y']

In [26]:
df_ant

,l_hip_x,l_hip_y,l_knee_x,l_knee_y,l_ankle_x,l_ankle_y,l_tibia_x,l_tibia_y,l_femur_x,l_femur_y
0,107.733394,-361.112112,130.113143,-845.492115,184.149087,-1239.500686,-54.035944,394.008571,-22.379749,484.380003
1,112.604582,-350.280776,140.102875,-782.229191,183.880384,-1241.898209,-43.777509,459.669018,-27.498293,431.948415
2,110.778499,-376.979206,145.040137,-829.152187,196.647998,-1179.951554,-51.607861,350.799367,-34.261638,452.172981
3,108.371615,-400.368206,139.998511,-887.184110,193.411557,-1168.444279,-53.413046,281.260169,-31.626896,486.815904
4,109.472398,-386.986860,151.076787,-879.063208,201.103875,-1165.892635,-50.027088,286.829427,-41.604389,492.076349
...,...,...,...,...,...,...,...,...,...,...
304,94.104964,-336.745144,135.177828,-762.599874,186.267584,-1123.438584,-51.089756,360.838709,-41.072864,425.854730
305,88.028521,-349.899483,127.370178,-737.610897,180.154902,-1132.372738,-52.784724,394.761842,-39.341657,387.711414
306,88.060778,-343.274659,129.263875,-751.073776,191.566231,-1106.596699,-62.302356,355.522922,-41.203097,407.799118
307,92.255395,-364.030771,132.946568,-729.269821,175.742054,-1128.854822,-42.795486,399.585001,-40.691173,365.239050


In [27]:
def angle_v2(vec1, vec2):
    # from google
    #import math
    import numpy as np

    np.array 
    
    # 각 벡터의 각도 계산 (x축 기준)
    angle1 = np.arctan2(vec1[:,1], vec1[:,0])
    angle2 = np.arctan2(vec2[:,1], vec2[:,0])

    # 두 각도의 차이 계산
    angle_diff_rad = angle2 - angle1

    # 절대값 및 360도 조정 (필요에 따라)
    angle_diff_deg = np.degrees(angle_diff_rad)
    #angle_diff_deg = np.where( angle_diff_deg < 0, angle_diff_deg + 360, angle_diff_deg )

    return angle_diff_deg

In [28]:
angle_v2(df_ant[['l_tibia_x','l_tibia_y']].values,       df_ant[['l_femur_x','l_femur_y']].values     )[0:50]

array([-5.16371287e+00, -1.79767682e+00, -4.03595486e+00, -7.03567651e+00,
       -5.06088187e+00, -4.96644414e+00, -2.54552512e+00,  6.43192002e-02,
       -4.97040854e+00, -3.83691453e+00, -2.75093801e+00,  8.68886148e+00,
        6.18176101e-03,  5.19519696e+00,  8.53532362e+00,  8.77758457e+00,
        7.11458615e+00,  5.44264705e+00,  7.87489029e+00,  1.04661778e+01,
        9.60392323e+00,  8.74941174e+00,  4.79621042e+00,  8.40062998e+00,
        1.37141829e+01,  6.95462724e+00,  1.48615793e+01,  1.22541789e+01,
        1.36836941e+01,  2.03636764e+01,  2.00373819e+01,  1.43410117e+01,
        1.31928436e+01,  1.20110776e+01,  1.16610268e+01,  1.66154916e+01,
        1.39506935e+01,  8.21912736e+00,  1.61088024e+01,  1.25350068e+01,
        7.65036823e+00,  1.12604337e+01,  2.80093750e+00, -4.78035606e+00,
        2.13512120e+00, -2.92023165e-01,  1.43134829e+00,  1.88269034e+00,
       -2.66140912e+00,  8.74666126e-01])

In [29]:
#lateral view
df_lat = df1[['torso_y', 'torso_z', 'waist_y','waist_z','l_hip_y','l_hip_z','l_knee_y','l_knee_z','l_ankle_y','l_ankle_z']]

In [30]:
df_lat['tor_wai_y'] = df_lat['torso_y'] - df_lat['waist_y']
df_lat['tor_wai_z'] = df_lat['torso_z'] - df_lat['waist_z']
df_lat['l_hip_wai_y'] = df_lat['waist_y'] - df_lat['l_hip_y']
df_lat['l_hip_wai_z'] = df_lat['waist_z'] - df_lat['l_hip_z']
df_lat['l_tibia_y'] = df_lat['l_knee_y'] - df_lat['l_ankle_y']
df_lat['l_tibia_z'] = df_lat['l_knee_z'] - df_lat['l_ankle_z']

In [31]:
#low back arch
angle_v2(df_lat[['tor_wai_y', 'tor_wai_z']].values, df_lat[['l_hip_wai_y','l_hip_wai_z']].values)[1:50]

array([ -62.54719542,  -11.06012915,  -80.97269804,    2.62709251,
         14.99326698,  -89.25237872,  -63.3815991 ,   -0.26042614,
        -24.9028247 ,  -73.97101989,   -3.30331933,  -36.56235767,
        -83.02349183, -108.96455313,  -42.89930668,  -51.75024168,
        -47.76977187,  -77.78896534,   51.60819288,  -36.78483847,
        -93.74432768, -110.87082237,  -34.65901758,  -96.923378  ,
        -82.9429951 ,  -84.39785456, -100.17739338,  -93.96623147,
         21.68484753,  -70.69237191,  -79.94370064,  102.44336389,
        -70.68811552,  -12.15477528,  -73.04854937,  -69.64634045,
        -84.03065565,  -22.43059972,  -99.7056252 ,   70.06684111,
       -121.78819129,  147.4716334 ,  -38.17930284,  -68.72112512,
        108.08335653, -128.27184878, -101.1547584 ,  -19.28047803,
         -3.102557  ])

In [32]:
#torso lean forward
angle_v2(df_lat[['l_tibia_y','l_tibia_z']].values, df_lat[['tor_wai_y', 'tor_wai_z']].values)[1:200]

array([-16.61425182,  41.37805958,  42.47734921,  -2.39771811,
        28.29936236,  12.97165889,   4.99077819,   7.99826437,
         5.9248035 ,   4.7922594 ,  43.67191683,  33.79538201,
        39.44835764,  59.59903394,  -4.94808855,   9.61123409,
        15.39250914,  34.66696678,   3.07346017,   4.99689565,
        34.20460139,  75.42272809,   4.31741554,  63.84869939,
        55.15498385,  46.9967544 ,  69.06165237,  69.23633146,
       -12.35568874,  57.79982718,  53.29294538,  26.92408633,
        32.75378033,  30.93503997,  77.27578007,  58.84143748,
        47.90793009,  -1.76164803,  25.56307689,  54.61242861,
        98.4698372 ,   3.84044709,  14.48679905, -25.14231545,
       -24.82710828,  85.04860234,  58.14685863,  11.22724876,
         8.84359693,  -3.75826802,  19.87090678,  59.40943877,
        40.13709268,  49.52415226,  13.11095302, -47.89157874,
        -4.38982727, -36.32823461,  12.34832983, -11.02036269,
       -35.69644183,  34.05809024, -30.34239689,   5.70

In [33]:
df_lat[0:50]

,torso_y,torso_z,waist_y,waist_z,l_hip_y,l_hip_z,l_knee_y,l_knee_z,l_ankle_y,l_ankle_z,tor_wai_y,tor_wai_z,l_hip_wai_y,l_hip_wai_z,l_tibia_y,l_tibia_z
0,-46.445630,2456.054574,-288.092188,2548.472704,-361.112112,2777.353548,-845.492115,2620.311328,-1239.500686,2662.635675,241.646558,-92.418130,73.019924,-228.880844,394.008571,-42.324347
1,-47.249917,2550.045473,-265.974698,2569.248279,-350.280776,2773.431775,-782.229191,2599.253251,-1241.898209,2504.922929,218.724780,-19.202807,84.306078,-204.183496,459.669018,94.330322
2,-69.252356,2541.725718,-266.384842,2573.346661,-376.979206,2613.978311,-829.152187,2375.841190,-1179.951554,2801.257686,197.132487,-31.620943,110.594364,-40.631650,350.799367,-425.416496
3,-115.668437,2576.150664,-336.098893,2561.674202,-400.368206,2844.906095,-887.184110,2615.618479,-1168.444279,2841.110996,220.430456,14.476462,64.269312,-283.231893,281.260169,-225.492518
4,-110.783699,2537.074331,-328.342306,2714.477583,-386.986860,2757.979525,-879.063208,2502.784563,-1165.892635,2717.337183,217.558607,-177.403251,58.644554,-43.501942,286.829427,-214.552620
5,-111.332508,2591.481082,-311.546950,2555.591107,-395.624221,2516.106114,-865.909685,2583.040121,-1270.220380,2715.475080,200.214442,35.889975,84.077271,39.484993,404.310695,-132.434959
6,-125.237247,2577.205081,-361.130902,2534.174287,-397.843840,2721.550529,-875.341364,2612.705380,-1206.791076,2627.951523,235.893655,43.030794,36.712938,-187.376242,331.449712,-15.246143
7,-130.184873,2560.991061,-348.766443,2552.464018,-425.935407,2692.530127,-837.646446,2626.224192,-1229.444491,2645.089912,218.581570,8.527043,77.168963,-140.066109,391.798046,-18.865720
8,-170.046139,2582.806094,-360.652397,2693.122669,-467.531643,2755.631069,-930.330633,2541.156739,-1202.552547,2754.292351,190.606258,-110.316575,106.879245,-62.508400,272.221914,-213.135612
9,-157.149208,2512.399861,-386.399733,2586.133380,-423.782650,2620.668140,-899.321567,2540.267016,-1234.152366,2687.624539,229.250524,-73.733519,37.382917,-34.534760,334.830799,-147.357524
